### ISSUE TITLE
Getting NullPointerException on signup using riot

### ISSUE THREAD

**Issue by Rohithzr** [kamax-io/mxisd#37]
I have configured a matrix homeserver (synapse) and am configuring the identity server (mxisd) but I am getting a null pointer exception on the basic settings.

Config

```
matrix.domain: 'https://idigid.com'
key.path: '/home/ubuntu/mxisd/sign.key'
storage.backend: 'sqlite'
storage.provider.sqlite.database: '/home/ubuntu/mxisd/mxisd.db'
threepid.medium.email.connectors.smtp.host: "email-smtp.us-west-2.amazonaws.com"
threepid.medium.email.connectors.smtp.port: 587
threepid.medium.email.connectors.smtp.tls: 1
threepid.medium.email.connectors.smtp.login: "*redacted*"
threepid.medium.email.connectors.smtp.password: "*redacted*"
threepid.medium.email.identity.from: "pinger@idigid.io"
```

It probably has something to do with 

[PlaceholderNotificationGenerator.java](https://github.com/kamax-io/mxisd/blob/e2b3920840ed3b2163fdca3272f7cb1da7e9383c/src/main/java/io/kamax/mxisd/threepid/notification/PlaceholderNotificationGenerator.java#L46)

Error

```
ubuntu@ip-172-31-19-34:~/mxisd$ java -jar build/libs/mxisd.jar
2017-11-23 07:49:49.944  INFO [           main] k.m.MatrixIdentityServerApplication : Starting MatrixIdentityServerApplication on ip-172-31-19-34 with PID 29678 (/home/ubuntu/mxisd/build/libs/mxisd.jar started by ubuntu in /home/ubuntu/mxisd)
2017-11-23 07:49:49.956  INFO [           main] k.m.MatrixIdentityServerApplication : No active profile set, falling back to default profiles: default
2017-11-23 07:49:55.399  INFO [           main]      i.k.m.c.rest.RestBackendConfig : --- REST backend config ---
2017-11-23 07:49:55.400  INFO [           main]      i.k.m.c.rest.RestBackendConfig : Enabled: false
2017-11-23 07:49:56.093  INFO [           main]    i.k.mxisd.config.ldap.LdapConfig : --- LDAP Config ---
2017-11-23 07:49:56.093  INFO [           main]    i.k.mxisd.config.ldap.LdapConfig : Enabled: false
2017-11-23 07:49:56.115  INFO [           main]  io.kamax.mxisd.config.MatrixConfig : --- Matrix config ---
2017-11-23 07:49:56.119  INFO [           main]  io.kamax.mxisd.config.MatrixConfig : Domain: https://idigid.com
2017-11-23 07:49:56.119  INFO [           main]  io.kamax.mxisd.config.MatrixConfig : Identity:
2017-11-23 07:49:56.124  INFO [           main]  io.kamax.mxisd.config.MatrixConfig : 	Servers: {"root":["https://matrix.org"]}
2017-11-23 07:49:56.184  INFO [           main]  io.kamax.mxisd.config.ServerConfig : --- Server config ---
2017-11-23 07:49:56.188  INFO [           main]  io.kamax.mxisd.config.ServerConfig : Name: https://idigid.com
2017-11-23 07:49:56.188  INFO [           main]  io.kamax.mxisd.config.ServerConfig : Port: 8090
2017-11-23 07:49:56.188  INFO [           main]  io.kamax.mxisd.config.ServerConfig : Public URL: https://https://idigid.com
2017-11-23 07:49:56.242  INFO [           main]  i.kamax.mxisd.config.sql.SqlConfig : --- Generic SQL Provider config ---
2017-11-23 07:49:56.242  INFO [           main]  i.kamax.mxisd.config.sql.SqlConfig : Enabled: false
2017-11-23 07:49:56.276  INFO [           main]      i.k.m.c.t.n.NotificationConfig : --- Notification config ---
2017-11-23 07:49:56.276  INFO [           main]      i.k.m.c.t.n.NotificationConfig : Handlers:
2017-11-23 07:49:56.302  INFO [           main]        i.k.m.c.t.medium.PhoneConfig : --- Phone config ---
2017-11-23 07:49:56.308  INFO [           main]        i.k.m.c.t.medium.PhoneConfig : Generator: template
2017-11-23 07:49:56.308  INFO [           main]        i.k.m.c.t.medium.PhoneConfig : Connector: twilio
2017-11-23 07:49:56.336  INFO [           main]       i.k.m.c.t.c.PhoneTwilioConfig : --- Phone SMS Twilio connector config ---
2017-11-23 07:49:56.339  INFO [           main]       i.k.m.c.t.c.PhoneTwilioConfig : Account SID:
2017-11-23 07:49:56.339  INFO [           main]       i.k.m.c.t.c.PhoneTwilioConfig : Sender number:
2017-11-23 07:49:56.342  INFO [           main] i.k.m.t.c.p.PhoneSmsTwilioConnector : Twilio API has been initiated
2017-11-23 07:49:56.380  INFO [           main]     i.k.m.c.t.m.EmailTemplateConfig : --- SMS Generator templates config ---
2017-11-23 07:49:56.381  INFO [           main]     i.k.m.c.t.m.EmailTemplateConfig : Invite: Built-in (threepids/sms/invite-template.txt)
2017-11-23 07:49:56.381  INFO [           main]     i.k.m.c.t.m.EmailTemplateConfig : Session validation:
2017-11-23 07:49:56.381  INFO [           main]     i.k.m.c.t.m.EmailTemplateConfig : 	Local: Built-in (threepids/sms/validate-local-template.txt)
2017-11-23 07:49:56.381  INFO [           main]     i.k.m.c.t.m.EmailTemplateConfig : 	Remote: Built-in (threepids/sms/validate-remote-template.txt)
2017-11-23 07:49:56.459  INFO [           main]        i.k.m.c.t.medium.EmailConfig : --- E-mail config ---
2017-11-23 07:49:56.460  INFO [           main]        i.k.m.c.t.medium.EmailConfig : From: pinger@dabster.io
2017-11-23 07:49:56.461  INFO [           main]        i.k.m.c.t.medium.EmailConfig : Name: Https://idigid.com Identity Server
2017-11-23 07:49:56.461  INFO [           main]        i.k.m.c.t.medium.EmailConfig : Generator: template
2017-11-23 07:49:56.461  INFO [           main]        i.k.m.c.t.medium.EmailConfig : Connector: smtp
2017-11-23 07:49:56.481  INFO [           main]     i.k.m.c.t.m.EmailTemplateConfig : --- E-mail Generator templates config ---
2017-11-23 07:49:56.482  INFO [           main]     i.k.m.c.t.m.EmailTemplateConfig : Invite: Built-in (threepids/email/invite-template.eml)
2017-11-23 07:49:56.482  INFO [           main]     i.k.m.c.t.m.EmailTemplateConfig : Session validation:
2017-11-23 07:49:56.482  INFO [           main]     i.k.m.c.t.m.EmailTemplateConfig : 	Local: Built-in (threepids/email/validate-local-template.eml)
2017-11-23 07:49:56.483  INFO [           main]     i.k.m.c.t.m.EmailTemplateConfig : 	Remote: Built-in (threepids/email/validate-remote-template.eml)
2017-11-23 07:49:56.519  INFO [           main]         i.k.m.c.t.c.EmailSmtpConfig : --- E-mail SMTP Connector config ---
2017-11-23 07:49:56.520  INFO [           main]         i.k.m.c.t.c.EmailSmtpConfig : Host: email-smtp.us-west-2.amazonaws.com
2017-11-23 07:49:56.520  INFO [           main]         i.k.m.c.t.c.EmailSmtpConfig : Port: 587
2017-11-23 07:49:56.520  INFO [           main]         i.k.m.c.t.c.EmailSmtpConfig : TLS Mode: 1
2017-11-23 07:49:56.520  INFO [           main]         i.k.m.c.t.c.EmailSmtpConfig : Login: *redacted*
2017-11-23 07:49:56.520  INFO [           main]         i.k.m.c.t.c.EmailSmtpConfig : Has password: true
2017-11-23 07:49:56.609  INFO [           main]     i.k.m.c.t.c.EmailSendGridConfig : --- Email SendGrid connector config ---
2017-11-23 07:49:56.610  INFO [           main]     i.k.m.c.t.c.EmailSendGridConfig : API key configured?: false
2017-11-23 07:49:56.612  INFO [           main]     i.k.m.c.t.c.EmailSendGridConfig : Identity: {"from":"","name":""}
2017-11-23 07:49:56.613  INFO [           main]     i.k.m.c.t.c.EmailSendGridConfig : Templates: {"invite":{"subject":"","body":{"text":"","html":""}},"session":{"local":{"body":{}},"remote":{"body":{}}}}
2017-11-23 07:49:56.626  INFO [           main]         i.k.m.n.NotificationManager : Found handler raw for medium msisdn
2017-11-23 07:49:56.626  INFO [           main]         i.k.m.n.NotificationManager : Found handler raw for medium email
2017-11-23 07:49:56.626  INFO [           main]         i.k.m.n.NotificationManager : Found handler sendgrid for medium email
2017-11-23 07:49:56.626  INFO [           main]         i.k.m.n.NotificationManager : --- Notification handler ---
2017-11-23 07:49:56.627  INFO [           main]         i.k.m.n.NotificationManager : 	Handler for msisdn: raw
2017-11-23 07:49:56.627  INFO [           main]         i.k.m.n.NotificationManager : 	Handler for email: sendgrid
2017-11-23 07:49:56.811  INFO [           main]   com.j256.ormlite.table.TableUtils : creating table 'invite_3pid'
2017-11-23 07:49:56.967  INFO [           main]   com.j256.ormlite.table.TableUtils : executed create table statement changed 0 rows: CREATE TABLE IF NOT EXISTS `invite_3pid` (`id` VARCHAR , `token` VARCHAR NOT NULL , `sender` VARCHAR NOT NULL , `medium` VARCHAR NOT NULL , `address` VARCHAR NOT NULL , `roomId` VARCHAR NOT NULL , `properties` VARCHAR , PRIMARY KEY (`id`) )
2017-11-23 07:49:56.978  INFO [           main]   com.j256.ormlite.table.TableUtils : creating table 'session_3pid'
2017-11-23 07:49:56.983  INFO [           main]   com.j256.ormlite.table.TableUtils : executed create table statement changed 0 rows: CREATE TABLE IF NOT EXISTS `session_3pid` (`id` VARCHAR , `creationTime` BIGINT NOT NULL , `server` VARCHAR NOT NULL , `medium` VARCHAR NOT NULL , `address` VARCHAR NOT NULL , `secret` VARCHAR NOT NULL , `attempt` INTEGER NOT NULL , `nextLink` VARCHAR , `token` VARCHAR NOT NULL , `validated` BOOLEAN , `validationTime` BIGINT , `isRemote` BOOLEAN NOT NULL , `remoteServer` VARCHAR , `remoteId` VARCHAR , `remoteSecret` VARCHAR , `remoteAttempt` INTEGER , `isRemoteValidated` BOOLEAN NOT NULL , PRIMARY KEY (`id`) )
2017-11-23 07:49:57.148  INFO [g-Init-Reporter]             com.mchange.v2.log.MLog : MLog clients using slf4j logging.
2017-11-23 07:49:57.238  INFO [           main]    com.mchange.v2.c3p0.C3P0Registry : Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]
2017-11-23 07:49:57.340  INFO [           main]  i.kamax.mxisd.config.sql.SqlConfig : --- Synapse SQL Provider config ---
2017-11-23 07:49:57.340  INFO [           main]  i.kamax.mxisd.config.sql.SqlConfig : Enabled: false
2017-11-23 07:49:57.409  INFO [           main]     i.k.mxisd.config.FirebaseConfig : --- Firebase configuration ---
2017-11-23 07:49:57.412  INFO [           main]     i.k.mxisd.config.FirebaseConfig : Enabled: false
2017-11-23 07:49:57.455  INFO [           main] i.k.m.c.RecursiveLookupBridgeConfig : --- Bridge integration lookups config ---
2017-11-23 07:49:57.460  INFO [           main] i.k.m.c.RecursiveLookupBridgeConfig : Enabled: false
2017-11-23 07:49:57.478  INFO [           main] l.s.RecursivePriorityLookupStrategy : 3PID Provider ForwarderProvider is enabled: true
2017-11-23 07:49:57.478  INFO [           main] l.s.RecursivePriorityLookupStrategy : 3PID Provider DnsLookupProvider is enabled: true
2017-11-23 07:49:57.479  INFO [           main] l.s.RecursivePriorityLookupStrategy : 3PID Provider RestThreePidProvider is enabled: false
2017-11-23 07:49:57.479  INFO [           main] l.s.RecursivePriorityLookupStrategy : 3PID Provider LdapThreePidProvider is enabled: false
2017-11-23 07:49:57.479  INFO [           main] l.s.RecursivePriorityLookupStrategy : 3PID Provider GenericSqlThreePidProvider is enabled: false
2017-11-23 07:49:57.479  INFO [           main] l.s.RecursivePriorityLookupStrategy : 3PID Provider SynapseSqlThreePidProvider is enabled: false
2017-11-23 07:49:57.479  INFO [           main] l.s.RecursivePriorityLookupStrategy : 3PID Provider GoogleFirebaseProvider is enabled: false
2017-11-23 07:49:57.481  INFO [           main] l.s.RecursivePriorityLookupStrategy : Found 2 providers
2017-11-23 07:49:57.488  INFO [           main] l.s.RecursivePriorityLookupStrategy : 	- io.kamax.mxisd.lookup.provider.ForwarderProvider
2017-11-23 07:49:57.488  INFO [           main] l.s.RecursivePriorityLookupStrategy : 	- io.kamax.mxisd.lookup.provider.DnsLookupProvider
2017-11-23 07:49:57.489  INFO [           main] l.s.RecursivePriorityLookupStrategy : Recursive lookup enabled: true
2017-11-23 07:49:57.489  INFO [           main] l.s.RecursivePriorityLookupStrategy : 127.0.0.0/8 is allowed for recursion
2017-11-23 07:49:57.490  INFO [           main] l.s.RecursivePriorityLookupStrategy : 10.0.0.0/8 is allowed for recursion
2017-11-23 07:49:57.491  INFO [           main] l.s.RecursivePriorityLookupStrategy : 172.16.0.0/12 is allowed for recursion
2017-11-23 07:49:57.491  INFO [           main] l.s.RecursivePriorityLookupStrategy : 192.168.0.0/16 is allowed for recursion
2017-11-23 07:49:57.491  INFO [           main] l.s.RecursivePriorityLookupStrategy : ::1/128 is allowed for recursion
2017-11-23 07:49:57.613  INFO [           main]     i.k.m.config.DnsOverwriteConfig : --- DNS Overwrite config ---
2017-11-23 07:49:57.616  INFO [           main]     i.k.m.config.DnsOverwriteConfig : Homeserver:
2017-11-23 07:49:57.620  INFO [           main]     i.k.m.config.DnsOverwriteConfig : 	Client: []
2017-11-23 07:49:57.620  INFO [           main]     i.k.m.config.DnsOverwriteConfig : 	Federation: []
2017-11-23 07:49:57.633  INFO [           main]  i.k.m.invitation.InvitationManager : Loading saved invites
2017-11-23 07:49:57.659  INFO [           main]  i.k.m.invitation.InvitationManager : Setting up invitation mapping refresh timer
2017-11-23 07:49:57.812  INFO [           main]  i.kamax.mxisd.config.SessionConfig : --- Session config ---
2017-11-23 07:49:57.817  INFO [           main]  i.kamax.mxisd.config.SessionConfig : Global Policy: {"validation":{"enabled":true,"forLocal":{"enabled":true,"toLocal":true,"toRemote":{"enabled":true,"server":"root"}},"forRemote":{"enabled":true,"toLocal":false,"toRemote":{"enabled":true,"server":"root"}}}}
2017-11-23 07:49:57.849  INFO [           main]    io.kamax.mxisd.config.ViewConfig : --- View config ---
2017-11-23 07:49:57.857  INFO [           main]    io.kamax.mxisd.config.ViewConfig : Session: {"local":{"onTokenSubmit":{"failure":"session/local/tokenSubmitFailure","success":"session/local/tokenSubmitSuccess"}},"localRemote":{"onTokenSubmit":{"failure":"session/local/tokenSubmitFailure","success":"session/localRemote/tokenSubmitSuccess"}},"remote":{"onRequest":{"failure":"session/remote/requestFailure","success":"session/remote/requestSuccess"},"onCheck":{"failure":"session/remote/checkFailure","success":"session/remote/checkSuccess"}}}
2017-11-23 07:49:57.956  INFO [           main]    i.k.m.directory.DirectoryManager : Directory providers:
2017-11-23 07:50:00.193  INFO [           main] k.m.MatrixIdentityServerApplication : Started MatrixIdentityServerApplication in 11.439 seconds (JVM running for 12.359)
2017-11-23 07:50:40.363  INFO [nio-8090-exec-1]  i.k.m.c.i.v1.SessionRestController : Request POST: http://localhost:8090/_matrix/identity/api/v1/validate/email/requestToken
2017-11-23 07:50:40.384  INFO [nio-8090-exec-1]   i.k.mxisd.session.SessionMananger : Server 127.0.0.1 is asking to create session for email:rohithzr@live.com (Attempt #1) - Next link: http://localhost:8080/#/register?client_secret=B7duTlxeyuuxZSVdzdYUAO4fs5fOmMNO&hs_url=https%3A%2F%2Fidigid.com&is_url=https%3A%2F%2Fidigid.com&session_id=tOymxqxZagAtlbhwGMtyQEOy
2017-11-23 07:50:40.396  INFO [nio-8090-exec-1]   i.k.mxisd.session.SessionMananger : No existing session for email:rohithzr@live.com
2017-11-23 07:50:40.397  INFO [nio-8090-exec-1]   i.k.mxisd.session.SessionMananger : Is 3PID bound to local domain? false
2017-11-23 07:50:40.401  INFO [nio-8090-exec-1]   i.k.mxisd.session.SessionMananger : Generated new session 1511423440397 to validate email:rohithzr@live.com from server 127.0.0.1
2017-11-23 07:50:40.401  INFO [nio-8090-exec-1]   i.k.mxisd.session.SessionMananger : Session 1511423440397 for email:rohithzr@live.com: sending remote-only validation notification
2017-11-23 07:50:40.421 ERROR [nio-8090-exec-1]     i.k.m.c.DefaultExceptionHandler : Unknown error when handling http://localhost:8090/_matrix/identity/api/v1/validate/email/requestToken

java.lang.NullPointerException: null
	at io.kamax.mxisd.threepid.notification.PlaceholderNotificationGenerator.populateForCommon(PlaceholderNotificationGenerator.java:46) ~[classes!/:na]
	at io.kamax.mxisd.threepid.notification.PlaceholderNotificationGenerator.populateForValidation(PlaceholderNotificationGenerator.java:79) ~[classes!/:na]
	at io.kamax.mxisd.threepid.notification.PlaceholderNotificationGenerator.populateForRemoteValidation(PlaceholderNotificationGenerator.java:86) ~[classes!/:na]
	at io.kamax.mxisd.threepid.connector.email.EmailSendGridNotificationHandler.sendForRemoteValidation(EmailSendGridNotificationHandler.java:115) ~[classes!/:na]
	at io.kamax.mxisd.notification.NotificationManager.sendforRemoteValidation(NotificationManager.java:82) ~[classes!/:na]
	at io.kamax.mxisd.session.SessionMananger.create(SessionMananger.java:168) ~[classes!/:na]
	at io.kamax.mxisd.controller.identity.v1.SessionRestController.init(SessionRestController.java:97) ~[classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) ~[spring-web-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) ~[spring-webmvc-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) ~[spring-webmvc-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) ~[spring-webmvc-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963) ~[spring-webmvc-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897) ~[spring-webmvc-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) [spring-webmvc-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872) [spring-webmvc-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) [spring-webmvc-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-8.5.14.jar!/:8.5.14]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105) [spring-web-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81) [spring-web-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) [spring-web-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]

2017-11-23 07:50:40.424  INFO [nio-8090-exec-1]     i.k.m.c.DefaultExceptionHandler : Request POST http://localhost:8090/_matrix/identity/api/v1/validate/email/requestToken - Error M_UNKNOWN: An internal server error occurred. If this error persists, please contact support with reference #1511423440423
```

**Comment by maxidor** [comment]
Could you confirm you're using the latest release, v0.6.0?

**Comment by Rohithzr** [comment]
@maxidor
I am following this guide here: https://github.com/kamax-io/mxisd/blob/master/docs/build.md

**Comment by maxidor** [comment]
@Rohithzr `matrix.domain` cannot be a URL, it has to be a domain. In your case, that would be `idigid.com`. I might or might not be related to the issue, but we'll see.

**Comment by Rohithzr** [comment]
@maxidor i tried it with 'idigid.com' on the first go, same error

**Comment by maxidor** [comment]
What is the output of `git describe --always --tags --dirty` in the cloned repository?

**Comment by Rohithzr** [comment]
There you go
```
ubuntu@ip-172-31-19-34:~/mxisd$  git describe --always --tags --dirty
v0.5.0-10-gaaa742f
```

**Comment by maxidor** [comment]
So for some reason the Sendgrid notification handler is being used, and I can't see any way that is being done unless you have more configuration than what you showed.

That would be done by setting a value for `notification.handler.email`

**Comment by Rohithzr** [comment]
What can I set it to disable it manually, i only have the setting i showed.
________________________________

**Comment by maxidor** [comment]
Add the following to the config file:
`notification.handler.email: raw`

**Comment by Rohithzr** [comment]
ok this works now.
thanks, also is there any place where we can connect? i basically have some questions and would be very helpful if you could help, basically regarding creating plugins for sms, email(ses) and other stuff.

**Comment by maxidor** [comment]
The best place is on Matrix directly, you can join #mxisd:kamax.io

**Comment by Rohithzr** [comment]
thanks a lot, ill join there now

**Comment by maxidor** [comment]
So after some digging, I found the bug. Could you remove the notification handler config option, update to latest master, and give it a try again please?

**Comment by Rohithzr** [comment]
@maxidor ok ill try this asap and let you know

**Comment by Rohithzr** [comment]
@maxidor yes it works
